Repository kusitms-wannafly/wannafly_be, pull requests merged in 2023-05, with the labels that each got.

#8 feat: 소셜 로그인 후 프론트 origin으로 리다이렉트
  src/main/java/com/kusitms/wannafly/auth/security/SecurityConfig.java
  src/main/java/com/kusitms/wannafly/auth/security/authentication/OAuthLoginSuccessHandler.java
  src/main/java/com/kusitms/wannafly/auth/security/oauth/OAuth2Member.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/com/kusitms/wannafly/support/mockapi/MockAuthController.java
Labels: 백엔드, 해결

#11 feat: 로그인 실패 처리와 LoginMember 구현
  src/main/java/com/kusitms/wannafly/auth/AuthConfig.java
  src/main/java/com/kusitms/wannafly/auth/LoginMember.java
  src/main/java/com/kusitms/wannafly/auth/LoginMemberResolver.java
  src/main/java/com/kusitms/wannafly/auth/security/SecurityConfig.java
  src/main/java/com/kusitms/wannafly/auth/security/authentication/OAuthLoginFailureHandler.java
  src/main/java/com/kusitms/wannafly/auth/security/authentication/OAuthLoginSuccessHandler.java
  src/main/java/com/kusitms/wannafly/auth/security/authentication/PrincipalOAuth2UserService.java
  src/main/java/com/kusitms/wannafly/auth/security/authoriization/UnAuthorizationEntryPoint.java
  src/main/resources/application-local.yml
  src/test/java/com/kusitms/wannafly/support/ControllerTest.java
Labels: 백엔드, 해결

#14 fix: 서브모듈 최신 커밋 가져오지 않는 오류 수정 & CORS 오류 수정
  .github/workflows/cicd.yml
  src/main/java/com/kusitms/wannafly/CorsConfig.java
  src/main/java/com/kusitms/wannafly/auth/security/SecurityConfig.java
  src/main/java/com/kusitms/wannafly/auth/security/authentication/OAuthLoginFailureHandler.java
  src/main/java/com/kusitms/wannafly/auth/security/authentication/OAuthLoginSuccessHandler.java
  src/main/resources/application-local.yml
Labels: 백엔드, 해결

#15 feat: 지원서 등록, 수정, 단건 조회 기능 구현
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  Dockerfile_dev
  src/docs/asciidoc/api.adoc
  src/main/java/com/kusitms/wannafly/applicationform/command/application/ApplicationFormService.java
  src/main/java/com/kusitms/wannafly/applicationform/command/domain/ApplicationAnswer.java
  src/main/java/com/kusitms/wannafly/applicationform/command/domain/ApplicationForm.java
  src/main/java/com/kusitms/wannafly/applicationform/command/domain/ApplicationFormRepository.java
  src/main/java/com/kusitms/wannafly/applicationform/command/domain/ApplicationItem.java
  src/main/java/com/kusitms/wannafly/applicationform/command/domain/ApplicationQuestion.java
  src/main/java/com/kusitms/wannafly/applicationform/command/domain/Semester.java
  src/main/java/com/kusitms/wannafly/applicationform/command/dto/ApplicationFormCreateRequest.java
  src/main/java/com/kusitms/wannafly/applicationform/command/dto/ApplicationFormMapper.java
  src/main/java/com/kusitms/wannafly/applicationform/command/dto/ApplicationFormUpdateRequest.java
  src/main/java/com/kusitms/wannafly/applicationform/command/dto/ApplicationItemCreateRequest.java
  src/main/java/com/kusitms/wannafly/applicationform/command/dto/ApplicationItemUpdateRequest.java
  src/main/java/com/kusitms/wannafly/applicationform/command/presentation/ApplicationFormController.java
  src/main/java/com/kusitms/wannafly/applicationform/query/ApplicationFormQueryController.java
  src/main/java/com/kusitms/wannafly/applicationform/query/ApplicationFormQueryRepository.java
  src/main/java/com/kusitms/wannafly/applicationform/query/ApplicationFormQueryService.java
  src/main/java/com/kusitms/wannafly/applicationform/query/dto/ApplicationFormResponse.java
  src/main/java/com/kusitms/wannafly/applicationform/query/dto/ApplicationItemResponse.java
  src/main/java/com/kusitms/wannafly/auth/LoginMember.java
  src/main/java/com/kusitms/wannafly/auth/security/authoriization/JwtAuthorizationFilter.java
  src/main/java/com/kusitms/wannafly/auth/security/oauth/OAuthProvider.java
  src/main/java/com/kusitms/wannafly/exception/ErrorCode.java
  src/main/resources/application.yml
  src/main/resources/db/migration/V2__application_form_add.sql
  src/main/resources/static/docs/api.html
  src/test/java/com/kusitms/wannafly/Acceptance/ApplicationFormAcceptanceTest.java
  src/test/java/com/kusitms/wannafly/Acceptance/fixture/AcceptanceFixture.java
  src/test/java/com/kusitms/wannafly/applicationform/command/application/ApplicationFormServiceTest.java
  src/test/java/com/kusitms/wannafly/applicationform/command/domain/ApplicationFormTest.java
  src/test/java/com/kusitms/wannafly/applicationform/command/domain/ApplicationQuestionTest.java
  src/test/java/com/kusitms/wannafly/applicationform/command/presentation/ApplicationFormControllerTest.java
  src/test/java/com/kusitms/wannafly/applicationform/query/ApplicationFormQueryControllerTest.java
  src/test/java/com/kusitms/wannafly/applicationform/query/ApplicationFormQueryServiceTest.java
  src/test/java/com/kusitms/wannafly/support/ControllerTest.java
  src/test/java/com/kusitms/wannafly/support/fixture/ApplicationFormFixture.java
Labels: 백엔드, api

#17 fix: cors PATCH 허용
  src/main/java/com/kusitms/wannafly/auth/security/SecurityConfig.java
Labels: 해결

#21 chore: spring actuator, prometheus 설정
  build.gradle
  src/main/resources/application.yml
Labels: 설정, 백엔드, 인프라

#22 feat: 맞춤법 검사 API 구현
  build.gradle
  src/docs/asciidoc/api.adoc
  src/main/java/com/kusitms/wannafly/command/grammar/application/GrammarService.java
  src/main/java/com/kusitms/wannafly/command/grammar/dto/GrammarRequest.java
  src/main/java/com/kusitms/wannafly/command/grammar/dto/GrammarResponse.java
  src/main/java/com/kusitms/wannafly/command/grammar/infrastructure/GrammarClient.java
  src/main/java/com/kusitms/wannafly/command/grammar/infrastructure/GrammarClientConfig.java
  src/main/java/com/kusitms/wannafly/command/grammar/infrastructure/GrammarServiceImpl.java
  src/main/java/com/kusitms/wannafly/command/grammar/presentation/GrammarController.java
  src/main/resources/application-local.yml
  src/test/java/com/kusitms/wannafly/Acceptance/AcceptanceTest.java
  src/test/java/com/kusitms/wannafly/WannaflyApplicationTests.java
  src/test/java/com/kusitms/wannafly/command/auth/token/JwtTokenProviderTest.java
  src/test/java/com/kusitms/wannafly/command/grammar/presentation/GrammarControllerTest.java
  src/test/java/com/kusitms/wannafly/support/ControllerTest.java
  src/test/java/com/kusitms/wannafly/support/ServiceTest.java
Labels: 백엔드, api

#29 fix : 카테고리 생성,조회,삭제 기능 수정
  src/docs/asciidoc/api.adoc
  src/main/java/com/kusitms/wannafly/command/applicationfolder/domain/ApplicationFolder.java
  src/main/java/com/kusitms/wannafly/command/applicationfolder/service/ApplicationFolderService.java
  src/main/java/com/kusitms/wannafly/command/category/domain/Category.java
  src/main/java/com/kusitms/wannafly/command/category/domain/CategoryRepository.java
  src/main/java/com/kusitms/wannafly/command/category/dto/CategoryCreateRequest.java
  src/main/java/com/kusitms/wannafly/command/category/presentation/CategoryController.java
  src/main/java/com/kusitms/wannafly/command/category/service/CategoryService.java
  src/main/java/com/kusitms/wannafly/command/category/service/CheckedCategoryService.java
  src/main/java/com/kusitms/wannafly/exception/ErrorCode.java
  src/main/java/com/kusitms/wannafly/query/controller/CategoryQueryController.java
  src/main/java/com/kusitms/wannafly/query/dto/CategoryResponse.java
  src/main/java/com/kusitms/wannafly/query/repository/CategoryQueryRepository.java
  src/main/java/com/kusitms/wannafly/query/service/CategoryQueryService.java
  src/main/resources/db/migration/V4__category_add.sql
  src/main/resources/static/docs/api.html
  src/test/java/com/kusitms/wannafly/Acceptance/AcceptanceTest.java
  src/test/java/com/kusitms/wannafly/Acceptance/ApplicationFolderAcceptanceTest.java
  src/test/java/com/kusitms/wannafly/Acceptance/ApplicationFormAcceptanceTest.java
  src/test/java/com/kusitms/wannafly/Acceptance/CategoryAcceptanceTest.java
  src/test/java/com/kusitms/wannafly/Acceptance/fixture/ApplicationFolderAcceptanceFixture.java
  src/test/java/com/kusitms/wannafly/Acceptance/fixture/AuthAcceptanceFixture.java
  src/test/java/com/kusitms/wannafly/Acceptance/fixture/CategoryAcceptanceFixture.java
  src/test/java/com/kusitms/wannafly/command/applicationfolder/domain/ApplicationFolderTest.java
  src/test/java/com/kusitms/wannafly/command/category/application/CategoryServiceTest.java
  src/test/java/com/kusitms/wannafly/command/category/domain/CategoryTest.java
  src/test/java/com/kusitms/wannafly/command/category/presentaion/CategoryControllerTest.java
  src/test/java/com/kusitms/wannafly/query/controller/CategoryQueryControllerTest.java
  src/test/java/com/kusitms/wannafly/query/service/CategoryQueryServiceTest.java
  src/test/java/com/kusitms/wannafly/support/ControllerTest.java
  src/test/java/com/kusitms/wannafly/support/fixture/CategoryFixture.java
Labels: 버그, 해결

#30 fix: 지원 문항 빈 문자열 허용
  src/main/java/com/kusitms/wannafly/command/applicationform/domain/value/ApplicationQuestion.java
  src/test/java/com/kusitms/wannafly/command/applicationform/domain/value/ApplicationQuestionTest.java
Labels: 백엔드, api

#31 feat: 지원 항목에 카테고리 연결 기능 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/kusitms/wannafly/command/applicationform/application/ApplicationItemService.java
  src/main/java/com/kusitms/wannafly/command/applicationform/domain/ApplicationItem.java
  src/main/java/com/kusitms/wannafly/command/applicationform/presentation/ApplicationFormController.java
  src/main/java/com/kusitms/wannafly/exception/ErrorCode.java
  src/main/java/com/kusitms/wannafly/query/controller/ApplicationFormQueryController.java
  src/main/java/com/kusitms/wannafly/query/dto/CategoryItemResponse.java
  src/main/java/com/kusitms/wannafly/query/repository/ApplicationItemQueryRepository.java
  src/main/java/com/kusitms/wannafly/query/service/ApplicationFormQueryService.java
  src/main/resources/db/migration/V5__add_category_id_item.sql
  src/main/resources/static/docs/api.html
  src/test/java/com/kusitms/wannafly/Acceptance/ApplicationFormAcceptanceTest.java
  src/test/java/com/kusitms/wannafly/Acceptance/CategoryAcceptanceTest.java
  src/test/java/com/kusitms/wannafly/Acceptance/fixture/ApplicationFormAcceptanceFixture.java
  src/test/java/com/kusitms/wannafly/command/applicationform/application/ApplicationFormServiceTest.java
  src/test/java/com/kusitms/wannafly/command/applicationform/application/ApplicationItemServiceTest.java
  src/test/java/com/kusitms/wannafly/command/applicationform/domain/ApplicationItemTest.java
  src/test/java/com/kusitms/wannafly/command/applicationform/presentation/ApplicationFormControllerTest.java
  src/test/java/com/kusitms/wannafly/query/controller/ApplicationFormQueryControllerTest.java
  src/test/java/com/kusitms/wannafly/query/service/ApplicationFormQueryServiceTest.java
  src/test/java/com/kusitms/wannafly/support/fixture/ApplicationFormFixture.java
Labels: 백엔드, api

#32 Realse 3 카테고리 기능 추가
  src/docs/asciidoc/api.adoc
  src/main/java/com/kusitms/wannafly/command/applicationfolder/domain/ApplicationFolder.java
  src/main/java/com/kusitms/wannafly/command/applicationfolder/service/ApplicationFolderService.java
  src/main/java/com/kusitms/wannafly/command/applicationform/application/ApplicationItemService.java
  src/main/java/com/kusitms/wannafly/command/applicationform/domain/ApplicationItem.java
  src/main/java/com/kusitms/wannafly/command/applicationform/domain/value/ApplicationQuestion.java
  src/main/java/com/kusitms/wannafly/command/applicationform/presentation/ApplicationFormController.java
  src/main/java/com/kusitms/wannafly/command/category/domain/Category.java
  src/main/java/com/kusitms/wannafly/command/category/domain/CategoryRepository.java
  src/main/java/com/kusitms/wannafly/command/category/dto/CategoryCreateRequest.java
  src/main/java/com/kusitms/wannafly/command/category/presentation/CategoryController.java
  src/main/java/com/kusitms/wannafly/command/category/service/CategoryService.java
  src/main/java/com/kusitms/wannafly/command/category/service/CheckedCategoryService.java
  src/main/java/com/kusitms/wannafly/exception/ErrorCode.java
  src/main/java/com/kusitms/wannafly/query/controller/ApplicationFormQueryController.java
  src/main/java/com/kusitms/wannafly/query/controller/CategoryQueryController.java
  src/main/java/com/kusitms/wannafly/query/dto/CategoryItemResponse.java
  src/main/java/com/kusitms/wannafly/query/dto/CategoryResponse.java
  src/main/java/com/kusitms/wannafly/query/repository/ApplicationItemQueryRepository.java
  src/main/java/com/kusitms/wannafly/query/repository/CategoryQueryRepository.java
  src/main/java/com/kusitms/wannafly/query/service/ApplicationFormQueryService.java
  src/main/java/com/kusitms/wannafly/query/service/CategoryQueryService.java
  src/main/resources/db/migration/V4__category_add.sql
  src/main/resources/db/migration/V5__add_category_id_item.sql
  src/main/resources/static/docs/api.html
  src/test/java/com/kusitms/wannafly/Acceptance/AcceptanceTest.java
  src/test/java/com/kusitms/wannafly/Acceptance/ApplicationFolderAcceptanceTest.java
  src/test/java/com/kusitms/wannafly/Acceptance/ApplicationFormAcceptanceTest.java
  src/test/java/com/kusitms/wannafly/Acceptance/CategoryAcceptanceTest.java
  src/test/java/com/kusitms/wannafly/Acceptance/fixture/ApplicationFolderAcceptanceFixture.java
  src/test/java/com/kusitms/wannafly/Acceptance/fixture/ApplicationFormAcceptanceFixture.java
  src/test/java/com/kusitms/wannafly/Acceptance/fixture/AuthAcceptanceFixture.java
  src/test/java/com/kusitms/wannafly/Acceptance/fixture/CategoryAcceptanceFixture.java
  src/test/java/com/kusitms/wannafly/command/applicationfolder/domain/ApplicationFolderTest.java
  src/test/java/com/kusitms/wannafly/command/applicationform/application/ApplicationFormServiceTest.java
  src/test/java/com/kusitms/wannafly/command/applicationform/application/ApplicationItemServiceTest.java
  src/test/java/com/kusitms/wannafly/command/applicationform/domain/ApplicationItemTest.java
  src/test/java/com/kusitms/wannafly/command/applicationform/presentation/ApplicationFormControllerTest.java
  src/test/java/com/kusitms/wannafly/command/category/application/CategoryServiceTest.java
  src/test/java/com/kusitms/wannafly/command/category/domain/CategoryTest.java
  src/test/java/com/kusitms/wannafly/command/category/presentaion/CategoryControllerTest.java
  src/test/java/com/kusitms/wannafly/query/controller/ApplicationFormQueryControllerTest.java
  src/test/java/com/kusitms/wannafly/query/controller/CategoryQueryControllerTest.java
  src/test/java/com/kusitms/wannafly/query/service/ApplicationFormQueryServiceTest.java
  src/test/java/com/kusitms/wannafly/query/service/CategoryQueryServiceTest.java
  src/test/java/com/kusitms/wannafly/support/ControllerTest.java
  src/test/java/com/kusitms/wannafly/support/fixture/ApplicationFormFixture.java
  src/test/java/com/kusitms/wannafly/support/fixture/CategoryFixture.java
Labels: 백엔드, api, 릴리즈

#34 feat: 지원서 총 개수 API 구현
  src/docs/asciidoc/api.adoc
  src/main/java/com/kusitms/wannafly/query/controller/ApplicationFormQueryController.java
  src/main/java/com/kusitms/wannafly/query/dto/FormTotalCountResponse.java
  src/main/java/com/kusitms/wannafly/query/repository/ApplicationFormQueryRepository.java
  src/main/java/com/kusitms/wannafly/query/service/ApplicationFormQueryService.java
  src/main/resources/static/docs/api.html
  src/test/java/com/kusitms/wannafly/Acceptance/ApplicationFormAcceptanceTest.java
  src/test/java/com/kusitms/wannafly/Acceptance/fixture/ApplicationFormAcceptanceFixture.java
  src/test/java/com/kusitms/wannafly/query/controller/ApplicationFormQueryControllerTest.java
Labels: 백엔드, api
